/**
 * Cavoke
 * API for cavoke interaction between main server and clients
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about external state sent from server (e.g. cards on the table, moves of other players)
 */
export interface GameState {
  /**
   * Any state information supplied by app\'s logic. May be any string (e.g. JSON)
   */
  state: string;
}

