/**
 * Cavoke
 * API for cavoke interaction between main server and clients
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about a move made by user (e.g. placement of an X in tictactoe)
 */
export interface GameMove {
  /**
   * Any information about the move supplied by QML. May be any string (e.g. JSON)
   */
  move: string;
}

