/**
 * Cavoke
 * API for cavoke interaction between main server and clients
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {User} from './user';
import {SessionInfo} from './sessionInfo';


/**
 * Metadata about a room
 */
export interface RoomInfo {
  room_id: string;
  invite_code: string;
  active_session?: SessionInfo;
  /**
   * User identifier from auth engine
   */
  host_member: string;
  /**
   * All users present in this room
   */
  members: Array<User>;
}

