/**
 * Cavoke
 * API for cavoke interaction between main server and clients
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Player} from './player';


/**
 * Metadata about a session (room to game pair)
 */
export interface SessionInfo {
  session_id: string;
  /**
   * cavoke game unique id
   */
  game_id: string;
  /**
   * 0 - NOT STARTED; 1 - RUNNING; 2 - FINISHED
   */
  status: number;
  invite_code: string;
  /**
   * User identifier from auth engine
   */
  host_id: string;
  players: Array<Player>;
}

