/**
 * Cavoke
 * API for cavoke interaction between main server and clients
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Statistics on a specific user in a specific game
 */
export interface UserGameStatistics {
  game_id?: string;
  time_played_sec?: number;
  games_played?: number;
  win_rate?: number;
}

